name: fitess_style_132
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.0.15
  webview_flutter: ^4.4.2
  in_app_review: ^2.0.6
  share_plus: ^7.2.2
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^9.8.0+1
  overlay_support: ^2.1.0
  table_calendar: ^3.0.9
  intl: ^0.19.0
  image_picker: ^1.0.7
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Pridi
      fonts:
        - asset: assets/fonts/Pridi-Medium.ttf
